import Head from "next/head";
import React from "react";

interface headerProps {
  title: string;
}
const Header = (props: headerProps) => {
  return (
    <Head>
      <title>{props.title ? props.title : "Banjara - Matrimony"}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

export default Header;
